package com.garminaiexporter

import org.json.JSONArray
import org.json.JSONObject

object GarminActivityMapper {
    fun map(id: String, payload: JSONObject): NormalizedActivity {
        val activity = payload.optJSONObject("activity") ?: JSONObject()
        val s = activity.optJSONObject("summaryDTO") ?: JSONObject()
        val sport = canonicalSport(activity.optJSONObject("activityTypeDTO")?.optString("typeKey", "other") ?: "other")
        fun m(key: String, label: String, unit: String = "", factor: Double = 1.0, source: String? = null) = number(s, key)?.let { CanonicalMetric(label, it * factor, unit, source) }
        val summary = listOfNotNull(m("distance", "Distance", "km", .001), m("duration", "Duration", "s"), m("movingDuration", "Moving duration", "s"), m("elapsedDuration", "Elapsed duration", "s"), m("averageSpeed", "Average speed", "m/s"), m("maxSpeed", "Maximum speed", "m/s"), m("elevationGain", "Elevation gain", "m"), m("elevationLoss", "Elevation loss", "m"), m("calories", "Calories", "kcal"), m("averageHR", "Average heart rate", "bpm"), m("maxHR", "Maximum heart rate", "bpm")) + if (sport == "running") listOfNotNull(number(s, "averageSpeed")?.takeIf { it > 0 }?.let { CanonicalMetric("Average pace", 1000 / it, "s/km") }) else emptyList()
        val training = listOfNotNull(m("trainingEffect", "Aerobic Training Effect", source = "Garmin"), m("anaerobicTrainingEffect", "Anaerobic Training Effect", source = "Garmin"), m("activityTrainingLoad", "Training Load", source = "Garmin"), m("beginPotentialStamina", "Starting Stamina", "%", source = "Garmin"), m("endPotentialStamina", "Ending Stamina", "%", source = "Garmin"))
        val dynamics = listOfNotNull(m("averageRunCadence", "Average cadence", if (sport == "running") "spm" else "rpm"), m("maxRunCadence", "Maximum cadence", if (sport == "running") "spm" else "rpm"), m("strideLength", "Stride length", "cm"), m("groundContactTime", "Ground contact time", "ms"), m("groundContactBalanceLeft", "Ground contact balance left", "%"), m("verticalOscillation", "Vertical oscillation", "cm"), m("verticalRatio", "Vertical ratio", "%"), m("avgRespirationRate", "Average respiration", "breaths/min"))
        val power = listOfNotNull(m("averagePower", "Average Power", "W"), m("maxPower", "Maximum Power", "W"), m("normalizedPower", "Normalized Power", "W"))
        val series = timeSeries(payload.optJSONObject("details"))
        val hr = zones(payload.optJSONArray("hrZones")); val pz = zones(payload.optJSONArray("powerZones"))
        return NormalizedActivity(source = "Garmin", id = id, title = activity.optString("activityName", "Garmin activity"), sportType = sport,
            startTime = text(s, "startTimeLocal") ?: text(s, "startTimeGMT"), timezone = text(s, "timeZoneUnitDTO") ?: text(s, "timezone"), device = text(s, "deviceName"), location = text(s, "locationName"),
            summary = summary, trainingMetrics = training, dynamics = dynamics, power = power, weather = weather(payload.optJSONObject("weather")), heartRateZones = hr, powerZones = pz,
            laps = rows(payload.optJSONObject("laps")?.optJSONArray("lapDTOs")), splits = rows(payload.optJSONObject("typedSplits")?.optJSONArray("splits")), timeSeries = series.first, timeSeriesColumns = series.second,
            sourceNotes = listOfNotNull("Training Effect, Training Load, and Stamina are Garmin-derived metrics.".takeIf { training.isNotEmpty() }, "Weather was supplied by Garmin or the configured historical fallback.".takeIf { payload.optJSONObject("weather") != null }),
            availability = linkedMapOf("Heart rate" to available(summary.any { "heart rate" in it.label.lowercase() }), "Power" to available(power.isNotEmpty()), "Running dynamics" to available(dynamics.isNotEmpty()), "Heart-rate zones" to available(hr.isNotEmpty()), "Power zones" to available(pz.isNotEmpty()), "Training Effect" to if (training.isNotEmpty()) "available from Garmin" else "unavailable from this source", "Relative Effort" to "unavailable from this source", "Time series" to available(series.first.isNotEmpty()), "GPS coordinates" to "excluded by privacy policy"), distanceMeters = number(s, "distance"))
    }

    private val descriptorNames = mapOf("sumElapsedDuration" to "elapsed_s", "sumDistance" to "distance_m", "directHeartRate" to "heart_rate_bpm", "directSpeed" to "speed_mps", "directElevation" to "elevation_m", "directPower" to "power_w", "directRunCadence" to "cadence_spm", "directPotentialStamina" to "potential_stamina_pct", "directAvailableStamina" to "stamina_pct", "directStrideLength" to "stride_length_cm", "directVerticalOscillation" to "vertical_oscillation_cm", "directVerticalRatio" to "vertical_ratio_pct", "directGroundContactTime" to "ground_contact_time_ms", "directGroundContactBalanceLeft" to "ground_contact_balance_left_pct", "directRespirationRate" to "respiration_bpm", "directGradeAdjustedSpeed" to "grade_adjusted_speed_mps", "directPerformanceCondition" to "performance_condition")
    private fun timeSeries(details: JSONObject?): Pair<List<ActivityRow>, List<String>> { val descriptors = details?.optJSONArray("metricDescriptors") ?: return emptyList<ActivityRow>() to emptyList(); val rawRows = details.optJSONArray("activityDetailMetrics") ?: return emptyList<ActivityRow>() to emptyList(); val columns = (0 until descriptors.length()).mapNotNull { i -> descriptors.optJSONObject(i)?.let { d -> descriptorNames[d.optString("key")]?.let { d.optInt("metricsIndex") to it } } }; return (0 until rawRows.length()).mapNotNull { i -> rawRows.optJSONObject(i)?.optJSONArray("metrics")?.let { values -> ActivityRow(columns.associate { (index, name) -> name to values.opt(index).takeUnless { it == JSONObject.NULL } }) } } to columns.map { it.second } }
    private fun rows(a: JSONArray?) = if (a == null) emptyList() else (0 until a.length()).mapNotNull { i -> a.optJSONObject(i)?.let { o -> ActivityRow(linkedMapOf("Lap" to (number(o, "lapIndex")?.toInt() ?: i + 1), "Distance" to number(o, "distance"), "Time" to number(o, "duration"), "Moving time" to number(o, "movingDuration"), "Avg HR" to number(o, "averageHR"), "Max HR" to number(o, "maxHR"), "Avg Power" to number(o, "averagePower"), "Max Power" to number(o, "maxPower"), "Cadence" to number(o, "averageRunCadence"), "Elevation gain" to number(o, "elevationGain")).filterValues { it != null }) } }
    private fun zones(a: JSONArray?) = if (a == null) emptyList() else (0 until a.length()).mapNotNull { i -> when (val v = a.opt(i)) { is Number -> v.toDouble(); is JSONObject -> number(v, "secsInZone"); else -> null } }
    private fun weather(o: JSONObject?) = o?.let { val source = text(it, "source") ?: "Garmin"; WeatherData(text(it, "condition"), number(it, "temperature"), number(it, "feelsLike"), number(it, "dewPoint"), number(it, "humidity"), text(it, "windDirection"), number(it, "windDirectionDegrees"), number(it, "windSpeed"), number(it, "windGust"), number(it, "precipitation"), text(it, "station"), source) }
    private fun number(o: JSONObject, k: String) = if (!o.has(k) || o.isNull(k)) null else o.optDouble(k, Double.NaN).takeUnless(Double::isNaN)
    private fun text(o: JSONObject, k: String) = o.optString(k).trim().takeIf { it.isNotEmpty() && !it.equals("null", true) }
    private fun canonicalSport(s: String) = when { s.contains("run", true) -> "running"; s.contains("cycl", true) || s.contains("bike", true) -> "cycling"; s.contains("walk", true) -> "walking"; s.contains("hik", true) -> "hiking"; s.contains("swim", true) -> "swimming"; else -> "other" }
    private fun available(v: Boolean) = if (v) "available" else "unavailable"
}
